name: webapp1
version: 1.0-SNAPSHOT
description: This is a simple Bukkit Plugin
author: Author

main: webapp.Main

commands:
  Hello:
    description: Shows a hello message to the player
    usage: |
      /<command> shows a hello message to the player